feat: add overview page
vitwit/resolute pull request #494
Opened 2023-06-19 09:33 UTC by Teja2045

#458

2023-06-20 09:45 UTC, akhilkumarpilli requested changes

2023-06-20 09:45 UTC, akhilkumarpilli commented on frontend/src/features/common/commonSlice.js
> +        console.log("get", action.payload);
```suggestion
```

2023-06-20 09:45 UTC, akhilkumarpilli commented on frontend/src/features/common/commonSlice.js
> +        const TokensPriceInfo = data.reduce((result, tokenInfo) => {
```suggestion
        const tokensPriceInfo = data.reduce((result, tokenInfo) => {
```

2023-06-20 09:45 UTC, akhilkumarpilli commented on frontend/src/pages/Home.js
> +    location.pathname.split("/")?.[location.pathname.split("/")?.length - 1];
Write as separate utility function if using in different files, if not define `location.pathname.split("/")` in separate variable and use it.

2023-06-20 09:45 UTC, akhilkumarpilli commented on frontend/src/pages/OverviewPage.jsx
> +  }, [tokenInfo]);
Avoid multiple useEffect and use a single state variable checking all three conditions at once.

2023-06-20 09:45 UTC, akhilkumarpilli commented on frontend/src/pages/general-overview/ChainDetails.js
> +    wallet.networks[chainID].network.config.currencies[0].coinDecimals;
What if any of the inner variables is undefined? Use `?` operator

2023-06-20 09:45 UTC, akhilkumarpilli commented on frontend/src/pages/general-overview/ChainDetails.js
> +              <Avatar sx={{ width: 24, height: 24 }} />
Don't we pass any avatar url here?

2023-06-21 04:55 UTC, akhilkumarpilli approved these changes

2023-06-21 09:47 UTC, aleem1314 approved these changes

2023-06-21 09:47 UTC, merged